//This file is automatically generated during the build process

using System;
namespace Tesserae.Tests
{

    internal class SamplesSourceCode
    {
        public static string GetCodeForSample(string sampleName)
        {
            switch(sampleName)
            {
                default: return "Missing sample code";
            }
        }
    }
}
